import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Blog Haven",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-11/12 mx-auto py-6">
        <nav className="mb-5">
        <div className="flex justify-between items-center">
          <div><p>Blog Haven</p></div>
          <div>
            <ul className="flex gap-6 items-center">
              <li><Link href="/">Home</Link></li>
              <li><Link href="/" >Profile</Link></li>
            </ul>
          </div>
        </div>
        </nav>
        <div>{children}</div>
        <footer></footer>
      </body>
    </html>
  );
}
